### ISSUE TITLE
DrissionPage.errors.NoRectError: 该元素没有位置及大小。报错了

### ISSUE THREAD

**Issue by wangshao123-cool** [JesterHey/hnqm_helper#1]
兄弟，遇到了问题
这个文件initialization.py里面
函数def go_video_page(course_type: str) -> None:
# 进入视频一次页
        click_page.ele(f'tag:a@@text():{course_type}').click()
这一行代码总是报错，DrissionPage.errors.NoRectError: 该元素没有位置及大小。

我做了测试，元素是存在的
element = click_page.ele(f'tag:a@@text():{course_type}')
    if element:
        print(f"找到元素: {element}")
        time.sleep(2)  # 等待元素可交互
        
        try:
            # 使用 JavaScript 滚动并点击元素
            click_page.run_js("arguments[0].scrollIntoView(true);", element)
            time.sleep(1)  # 等待滚动完成
            click_page.run_js("arguments[0].click();", element)
            print("使用 JavaScript 点击元素")
然后报DrissionPage.errors.PageDisconnectedError: 与页面的连接已断开。

**Comment by JesterHey** [comment]
Hi!感谢反馈。请检查自己在使用时是否挂了代理（如果是请关闭），以及网络环境是否通畅。
除此以外，可能的解决方式：
在语句
```python
click_page.ele(f'tag:a@@text():{course_type}').click()
```
之前添加
```python
time.sleep(2)
```

如果您已经找到其他方案，欢迎分享，同时欢迎PR!

**Comment by wangshao123-cool** [comment]
HI！你这个方法，我已经尝试过了，还是一样的报错
代理我也没开，网络也是正常的
```time.sleep(2)
click_page.ele(f'tag:a@@text():{course_type}').click()
```
`
2024-07-01 11:26:32.315 | DEBUG    | get_info:get_info:90 - 读取课程信息中...
2024-07-01 11:26:43.714 | SUCCESS  | get_info:get_info:111 - 课程信息读取完成,共有19门课程
2024-07-01 11:26:43.720 | DEBUG    | __main__:init:118 - 存在课程数量小于10的课程类型:['培训']
2024-07-01 11:26:43.720 | DEBUG    | __main__:init:119 - 正在进行初始化...
2024-07-01 11:26:43.749 | INFO     | get_info:login:27 - 当前页面已登录
Traceback (most recent call last):
  File "C:\Users\77858\Desktop\闲杂\hnqm_helper-main\initialization.py", line 134, in <module>
    init()
  File "C:\Users\77858\Desktop\闲杂\hnqm_helper-main\initialization.py", line 130, in init
    click_videoes(study_type=study_type, class_info=class_info)
  File "C:\Users\77858\Desktop\闲杂\hnqm_helper-main\initialization.py", line 95, in click_videoes
    go_video_page('选修')
  File "C:\Users\77858\Desktop\闲杂\hnqm_helper-main\initialization.py", line 73, in go_video_page
    click_page.ele(f'tag:a@@text():{course_type}').click()
  File "C:\Users\77858\Desktop\闲杂\hnqm_helper-main\venv\Lib\site-packages\DrissionPage\_units\clicker.py", line 30, in __call__
    return self.left(by_js, timeout, wait_stop)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\77858\Desktop\闲杂\hnqm_helper-main\venv\Lib\site-packages\DrissionPage\_units\clicker.py", line 79, in left
    raise NoRectError
DrissionPage.errors.NoRectError: 该元素没有位置及大小。
`

**Comment by wangshao123-cool** [comment]
HI！你的方法之前我就试过也是报错，网络也没问题，代理也关了
`time.sleep(2`
`click_page.ele(f'tag:a@@text():{course_type}').click()`
```
Traceback (most recent call last):
  File "C:\Users\77858\Desktop\闲杂\hnqm_helper-main\initialization.py", line 134, in <module>
    init()
  File "C:\Users\77858\Desktop\闲杂\hnqm_helper-main\initialization.py", line 130, in init
    click_videoes(study_type=study_type, class_info=class_info)
  File "C:\Users\77858\Desktop\闲杂\hnqm_helper-main\initialization.py", line 95, in click_videoes
    go_video_page('选修')
  File "C:\Users\77858\Desktop\闲杂\hnqm_helper-main\initialization.py", line 73, in go_video_page
    click_page.ele(f'tag:a@@text():{course_type}').click()
  File "C:\Users\DrissionPage\_units\clicker.py", line 30, in __call__
    return self.left(by_js, timeout, wait_stop)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DrissionPage\_units\clicker.py", line 79, in left
    raise NoRectError
DrissionPage.errors.NoRectError: 该元素没有位置及大小。

```
